(defvar files
  (mapcar #'expand-file-name
          (directory-files-recursively "~/src/noweb/src" ".*\\.nw$")))
(defvar files-parsed (eval `(peg-noweb-parse-files ,@files)))
(peg-noweb-parse-files (expand-file-name "~/src/whyse/src/whyse.nw"))
(defun peg-noweb-document-deparse-diff (document filename)
  "Deparse the DOCUMENT then diff against the tool syntax generated by Noweb's `markup' binary."
  (if (not (string= (expand-file-name (car document))
                    (expand-file-name filename)))
      (error "The filename in the DOCUMENT argument (%s) and the FILENAME argument (%s) must be `string='."
             (car document)
             filename))
  (let* ((deparsed (peg-noweb-document-deparse document))
         (deparsed-buffer (create-file-buffer (car document)))
         (deparsed (with-current-buffer deparsed-buffer
                     (insert deparsed)
                     (buffer-string)))
         (markup-buffer (create-file-buffer filename))
         (markup (progn (call-process "/usr/local/noweb/lib/markup" nil
                                      markup-buffer nil filename)
                        (with-current-buffer markup-buffer
                          (buffer-string)))))
    (string= deparsed markup)))
(defvar results
  (cl-loop for document in files-parsed collect
           (cons (car document) (peg-noweb-document-deparse-diff document (car document)))))
(if (rassq (not t) results)
    (error "Not all documents deparsed correctly."))
