(defvar files
  (mapcar #'expand-file-name
          (directory-files-recursively "~/src/noweb/src" ".*\\.nw$")))
(defun document-deparse-diff (document filename)
  "Deparse the DOCUMENT then diff against the tool syntax generated by Noweb's `markup' binary."
  (if (not (string= (expand-file-name (car document))
                    (expand-file-name filename)))
      (error "The filename in the DOCUMENT argument (%s) and the FILENAME argument (%s) must be `string='."
             (car document)
             filename))
  (let* ((deparsed (peg-noweb-document-deparse document))
         (deparsed-buffer (create-file-buffer (car document)))
         (deparsed (with-current-buffer deparsed-buffer
                     (insert deparsed)
                     (buffer-string)))
         (markup-buffer (create-file-buffer filename))
         (markup (progn (call-process "/usr/local/noweb/lib/markup" nil
                                      markup-buffer nil filename)
                        (with-current-buffer markup-buffer
                          (buffer-string)))))
    (string= deparsed markup)))
(defun document-deparse-diff-buffers (document filename)
  "Deparse the DOCUMENT (a list of chunks, with the car being the filename
string the parsed chunks were taken from) then diff against the tool
syntax generated by Noweb's `markup' binary."
  (if (not (string= (expand-file-name (car document))
                    (expand-file-name filename)))
      (error "The filename in the DOCUMENT argument (%s) and the FILENAME argument (%s) must be `string='."
             (car document)
             filename))
  (let* ((deparsed (peg-noweb-document-deparse document))
         (deparsed-buffer (with-current-buffer (get-buffer-create "deparsed-buffer")
                            (erase-buffer)
                            (current-buffer)))
         (markup-buffer (with-current-buffer (get-buffer-create "markup-buffer")
                          (erase-buffer)
                          (current-buffer)))
         (markup (call-process "/usr/local/noweb/lib/markup" nil
                               markup-buffer nil filename)))
    (diff-buffers (with-current-buffer markup-buffer
                    (current-buffer))
                  (with-current-buffer deparsed-buffer
                    (insert deparsed)
                    (current-buffer)))))
(defvar results
  (cl-loop for document in (eval `(peg-noweb-parse-files ,@files)) collect
           (cons (car document) (document-deparse-diff document (car document)))))
(if (rassq (not t) results)
    (error "Not all documents deparsed correctly."))
(defun do-diff-next-noweb-web ()
  (if-let* ((f (car (rassq (not t) results))))
      (progn (setf results (assq-delete-all f results))
             (document-deparse-diff-buffers (cl-first (peg-noweb-parse-files f)) f))))
;; (do-diff-next-noweb-web)

(defvar peg-noweb-filename (expand-file-name "~/src/peg-noweb/src/peg-noweb.nw"))
(defvar peg-noweb (peg-noweb-parse-files peg-noweb-filename))
(document-deparse-diff-buffers (car peg-noweb) peg-noweb-filename)

(defvar whyse-filename (expand-file-name "~/src/whyse/src/whyse.nw"))
(defvar whyse (peg-noweb-parse-files whyse-filename))
(document-deparse-diff-buffers (car whyse) whyse-filename)
