(defvar tool (peg-noweb-parse-files (expand-file-name "~/src/peg-noweb/src/peg-noweb.nw")))
(defvar no-weave "/home/bryce/src/noweb/src/shell/noweave.nw")
(defvar no-weave-parsed (peg-noweb-parse-files no-weave))
(defvar document (peg-noweb-document 0 no-weave-parsed))
(defvar markup
  (progn (call-process "/usr/local/noweb/lib/markup" nil
                       (setq no-weave-buffer (create-file-buffer no-weave))
                       nil no-weave)
         (with-current-buffer no-weave-buffer
           (buffer-string))))

(with-current-buffer (get-buffer-create "deparse-buffer")
  (insert (peg-noweb-document-deparse document)))
;; (ediff-buffers no-weave-buffer (get-buffer-create "deparse-buffer"))

(defvar files
  (mapcar #'expand-file-name (directory-files-recursively "~/src/noweb/src"
                                                          ".*\\.nw$")))

;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/awk/noindex.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/awk/tohtml.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/c/Makefile.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/c/columns.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/c/doc.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/c/errors.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/c/fakepretty.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/c/finduses.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/c/getline.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/c/main.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/c/markmain.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/c/markup.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/c/match.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/c/mnt.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/c/modtrees.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/c/modules.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/c/notangle.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/c/nwmktemp.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/c/pretty.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/c/readme.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/c/recognize.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/c/strsave.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/icon/asdldefs.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/icon/cdefs.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/icon/defns.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/icon/disambiguate.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/icon/docs2comments.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/icon/elide.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/icon/htmltoc.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/icon/icondefs.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/icon/l2h.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/icon/lrtldefs.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/icon/mmixdefs.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/icon/noidx.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/icon/noindex.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/icon/noxref.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/icon/nwl2h.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/icon/pascaldefs.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/icon/pdcached.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/icon/pipedocs.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/icon/promeladefs.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/icon/smldefs.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/icon/texdefs.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/icon/tohtml.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/icon/xchunks.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/icon/yaccdefs.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/lib/noxref.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/shell/notangle.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/shell/noweave.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/shell/noweb.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/tex/support.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/xdoc/docdate.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/xdoc/htmltoc.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/xdoc/manpage.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/xdoc/nodefs.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/xdoc/noindex.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/xdoc/noroff.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/xdoc/noroots.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/xdoc/nowebfilters.nw")
;; (peg-noweb-parse-files "/home/bryce/src/noweb/src/xdoc/sl2h.nw")

;; FIXME: the following files cannot be parsed without
;; `wrong-type-argument' errors when `make-symol' is called during
;; `peg-postprocess'.
(peg-noweb-parse-files "/home/bryce/src/noweb/src/icon/totex.nw"); (nl . "\n")
(peg-noweb-parse-files "/home/bryce/src/noweb/src/shell/roff.nw"); (defn . "delay")
(peg-noweb-parse-files "/home/bryce/src/noweb/src/shell/toroff.nw"); (defn . "delay")
(peg-noweb-parse-files "/home/bryce/src/noweb/src/tex/multlang.nw"); (defn . "\\codehsize")
(peg-noweb-parse-files "/home/bryce/src/noweb/src/lib/toascii.nw"); (defn . "delay")
(peg-noweb-parse-files "/home/bryce/src/noweb/src/awk/noidx.nw"); (defn . "lines")
(peg-noweb-parse-files "/home/bryce/src/noweb/src/awk/totex.nw"); (defn . "lines")
